//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.04 at 05:29:57 PM ICT 
//


package org.opencps.notificationmgt.message;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProcessOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DossierId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PaymentFileId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EventName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PatternConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PlId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JspRedirect" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InfomationList" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processOrderId",
    "dossierId",
    "paymentFileId",
    "eventName",
    "patternConfig",
    "plId",
    "jspRedirect",
    "infomationList"
})
@XmlRootElement(name = "SendNotificationMessage")
public class SendNotificationMessage {

    @XmlElement(name = "ProcessOrderId", required = true)
    protected String processOrderId;
    @XmlElement(name = "DossierId", required = true)
    protected String dossierId;
    @XmlElement(name = "PaymentFileId", required = true)
    protected String paymentFileId;
    @XmlElement(name = "EventName", required = true)
    protected String eventName;
    @XmlElement(name = "PatternConfig", required = true)
    protected String patternConfig;
    @XmlElement(name = "PlId", required = true)
    protected String plId;
    @XmlElement(name = "JspRedirect", required = true)
    protected String jspRedirect;
    @XmlElement(name = "InfomationList", required = true)
    protected List<SendNotificationMessage.InfomationList> infomationList;

    public void setInfomationList(
			List<SendNotificationMessage.InfomationList> infomationList) {
		this.infomationList = infomationList;
	}

	/**
     * Gets the value of the processOrderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessOrderId() {
        return processOrderId;
    }

    /**
     * Sets the value of the processOrderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessOrderId(String value) {
        this.processOrderId = value;
    }

    /**
     * Gets the value of the dossierId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDossierId() {
        return dossierId;
    }

    /**
     * Sets the value of the dossierId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDossierId(String value) {
        this.dossierId = value;
    }

    /**
     * Gets the value of the paymentFileId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentFileId() {
        return paymentFileId;
    }

    /**
     * Sets the value of the paymentFileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentFileId(String value) {
        this.paymentFileId = value;
    }

    /**
     * Gets the value of the eventName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * Sets the value of the eventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventName(String value) {
        this.eventName = value;
    }

    /**
     * Gets the value of the patternConfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatternConfig() {
        return patternConfig;
    }

    /**
     * Sets the value of the patternConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatternConfig(String value) {
        this.patternConfig = value;
    }

    /**
     * Gets the value of the plId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlId() {
        return plId;
    }

    /**
     * Sets the value of the plId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlId(String value) {
        this.plId = value;
    }

    /**
     * Gets the value of the jspRedirect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJspRedirect() {
        return jspRedirect;
    }

    /**
     * Sets the value of the jspRedirect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJspRedirect(String value) {
        this.jspRedirect = value;
    }

    /**
     * Gets the value of the infomationList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infomationList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfomationList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SendNotificationMessage.InfomationList }
     * 
     * 
     */
    public List<SendNotificationMessage.InfomationList> getInfomationList() {
        if (infomationList == null) {
            infomationList = new ArrayList<SendNotificationMessage.InfomationList>();
        }
        return this.infomationList;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userId",
        "emailAddress",
        "fullName",
        "phoneNumber"
    })
    public static class InfomationList {

        @XmlElement(name = "UserId", required = true)
        protected String userId;
        @XmlElement(name = "EmailAddress", required = true)
        protected String emailAddress;
        @XmlElement(name = "FullName", required = true)
        protected String fullName;
        @XmlElement(name = "PhoneNumber", required = true)
        protected String phoneNumber;

        /**
         * Gets the value of the userId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserId(String value) {
            this.userId = value;
        }

        /**
         * Gets the value of the emailAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmailAddress() {
            return emailAddress;
        }

        /**
         * Sets the value of the emailAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmailAddress(String value) {
            this.emailAddress = value;
        }

        /**
         * Gets the value of the fullName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the phoneNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhoneNumber() {
            return phoneNumber;
        }

        /**
         * Sets the value of the phoneNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhoneNumber(String value) {
            this.phoneNumber = value;
        }

    }

}
