//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.14 at 04:48:19 PM ICT 
//


package org.opencps.notificationmgt.fac;

import javax.xml.bind.annotation.XmlRegistry;

import org.opencps.notificationmgt.message.SendNotificationMessage;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class SendNotificationMessageFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vn
     * 
     */
    public SendNotificationMessageFactory() {
    }

    /**
     * Create an instance of {@link SendNotificationMessage }
     * 
     */
    public SendNotificationMessage createSendNotificationMessage() {
        return new SendNotificationMessage();
    }

    /**
     * Create an instance of {@link SendNotificationMessage.Infomations }
     * 
     */
    public SendNotificationMessage.Infomations createSendNotificationMessageInfomations() {
        return new SendNotificationMessage.Infomations();
    }

    /**
     * Create an instance of {@link SendNotificationMessage.Infomations.Infomation }
     * 
     */
    public SendNotificationMessage.Infomations.Infomation createSendNotificationMessageInfomationsInfomation() {
        return new SendNotificationMessage.Infomations.Infomation();
    }

}
