//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.06 at 02:19:50 PM ICT 
//


package org.opencps.postal.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeliveryID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ItemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AcceptancePOSCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ToPOSCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SendingTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeliveryTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeliveryTimes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReceiverName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InputTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CreateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastUpdateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsDeliverable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsReturn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeliveryNote" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CauseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CauseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SolutionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SolutionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliveryID",
    "itemCode",
    "customerCode",
    "acceptancePOSCode",
    "toPOSCode",
    "sendingTime",
    "deliveryTime",
    "deliveryTimes",
    "receiverName",
    "inputTime",
    "createTime",
    "lastUpdateTime",
    "isDeliverable",
    "isReturn",
    "deliveryNote",
    "causeCode",
    "causeName",
    "solutionCode",
    "solutionName"
})
@XmlRootElement(name = "PostalDelivery")
public class PostalDelivery {

    @XmlElement(name = "DeliveryID", required = true)
    protected String deliveryID;
    @XmlElement(name = "ItemCode", required = true)
    protected String itemCode;
    @XmlElement(name = "CustomerCode", required = true)
    protected String customerCode;
    @XmlElement(name = "AcceptancePOSCode", required = true)
    protected String acceptancePOSCode;
    @XmlElement(name = "ToPOSCode", required = true)
    protected String toPOSCode;
    @XmlElement(name = "SendingTime", required = true)
    protected String sendingTime;
    @XmlElement(name = "DeliveryTime", required = true)
    protected String deliveryTime;
    @XmlElement(name = "DeliveryTimes", required = true)
    protected String deliveryTimes;
    @XmlElement(name = "ReceiverName", required = true)
    protected String receiverName;
    @XmlElement(name = "InputTime", required = true)
    protected String inputTime;
    @XmlElement(name = "CreateTime", required = true)
    protected String createTime;
    @XmlElement(name = "LastUpdateTime", required = true)
    protected String lastUpdateTime;
    @XmlElement(name = "IsDeliverable", required = true)
    protected String isDeliverable;
    @XmlElement(name = "IsReturn", required = true)
    protected String isReturn;
    @XmlElement(name = "DeliveryNote", required = true)
    protected String deliveryNote;
    @XmlElement(name = "CauseCode", required = true)
    protected String causeCode;
    @XmlElement(name = "CauseName", required = true)
    protected String causeName;
    @XmlElement(name = "SolutionCode", required = true)
    protected String solutionCode;
    @XmlElement(name = "SolutionName", required = true)
    protected String solutionName;

    /**
     * Gets the value of the deliveryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryID() {
        return deliveryID;
    }

    /**
     * Sets the value of the deliveryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryID(String value) {
        this.deliveryID = value;
    }

    /**
     * Gets the value of the itemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * Sets the value of the itemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemCode(String value) {
        this.itemCode = value;
    }

    /**
     * Gets the value of the customerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * Sets the value of the customerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCode(String value) {
        this.customerCode = value;
    }

    /**
     * Gets the value of the acceptancePOSCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptancePOSCode() {
        return acceptancePOSCode;
    }

    /**
     * Sets the value of the acceptancePOSCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptancePOSCode(String value) {
        this.acceptancePOSCode = value;
    }

    /**
     * Gets the value of the toPOSCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToPOSCode() {
        return toPOSCode;
    }

    /**
     * Sets the value of the toPOSCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToPOSCode(String value) {
        this.toPOSCode = value;
    }

    /**
     * Gets the value of the sendingTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendingTime() {
        return sendingTime;
    }

    /**
     * Sets the value of the sendingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendingTime(String value) {
        this.sendingTime = value;
    }

    /**
     * Gets the value of the deliveryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * Sets the value of the deliveryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryTime(String value) {
        this.deliveryTime = value;
    }

    /**
     * Gets the value of the deliveryTimes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryTimes() {
        return deliveryTimes;
    }

    /**
     * Sets the value of the deliveryTimes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryTimes(String value) {
        this.deliveryTimes = value;
    }

    /**
     * Gets the value of the receiverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * Sets the value of the receiverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverName(String value) {
        this.receiverName = value;
    }

    /**
     * Gets the value of the inputTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputTime() {
        return inputTime;
    }

    /**
     * Sets the value of the inputTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputTime(String value) {
        this.inputTime = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateTime(String value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the lastUpdateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * Sets the value of the lastUpdateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateTime(String value) {
        this.lastUpdateTime = value;
    }

    /**
     * Gets the value of the isDeliverable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDeliverable() {
        return isDeliverable;
    }

    /**
     * Sets the value of the isDeliverable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDeliverable(String value) {
        this.isDeliverable = value;
    }

    /**
     * Gets the value of the isReturn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsReturn() {
        return isReturn;
    }

    /**
     * Sets the value of the isReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsReturn(String value) {
        this.isReturn = value;
    }

    /**
     * Gets the value of the deliveryNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryNote() {
        return deliveryNote;
    }

    /**
     * Sets the value of the deliveryNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryNote(String value) {
        this.deliveryNote = value;
    }

    /**
     * Gets the value of the causeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCauseCode() {
        return causeCode;
    }

    /**
     * Sets the value of the causeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCauseCode(String value) {
        this.causeCode = value;
    }

    /**
     * Gets the value of the causeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCauseName() {
        return causeName;
    }

    /**
     * Sets the value of the causeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCauseName(String value) {
        this.causeName = value;
    }

    /**
     * Gets the value of the solutionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolutionCode() {
        return solutionCode;
    }

    /**
     * Sets the value of the solutionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolutionCode(String value) {
        this.solutionCode = value;
    }

    /**
     * Gets the value of the solutionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolutionName() {
        return solutionName;
    }

    /**
     * Sets the value of the solutionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolutionName(String value) {
        this.solutionName = value;
    }

}
