//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.06 at 02:23:31 PM ICT 
//


package org.opencps.postal.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AcceptancePoscode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestinationPoscode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SendingTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SenderFullname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SenderAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SenderTel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReceiverFullname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReceiverAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReceiverTel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ValueAddedServiceList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MainFreight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VasFreight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodFreight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WeightConvert" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Length" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Opt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemCode",
    "dataCode",
    "codAmount",
    "acceptancePoscode",
    "destinationPoscode",
    "sendingTime",
    "senderFullname",
    "senderAddress",
    "senderTel",
    "receiverFullname",
    "receiverAddress",
    "receiverTel",
    "valueAddedServiceList",
    "mainFreight",
    "vasFreight",
    "codFreight",
    "customerCode",
    "weight",
    "weightConvert",
    "width",
    "length",
    "height",
    "opt"
})
@XmlRootElement(name = "PostalAcceptance")
public class PostalAcceptance {

    @XmlElement(name = "ItemCode", required = true)
    protected String itemCode;
    @XmlElement(name = "DataCode", required = true)
    protected String dataCode;
    @XmlElement(name = "CodAmount", required = true)
    protected String codAmount;
    @XmlElement(name = "AcceptancePoscode", required = true)
    protected String acceptancePoscode;
    @XmlElement(name = "DestinationPoscode", required = true)
    protected String destinationPoscode;
    @XmlElement(name = "SendingTime", required = true)
    protected String sendingTime;
    @XmlElement(name = "SenderFullname", required = true)
    protected String senderFullname;
    @XmlElement(name = "SenderAddress", required = true)
    protected String senderAddress;
    @XmlElement(name = "SenderTel", required = true)
    protected String senderTel;
    @XmlElement(name = "ReceiverFullname", required = true)
    protected String receiverFullname;
    @XmlElement(name = "ReceiverAddress", required = true)
    protected String receiverAddress;
    @XmlElement(name = "ReceiverTel", required = true)
    protected String receiverTel;
    @XmlElement(name = "ValueAddedServiceList", required = true)
    protected String valueAddedServiceList;
    @XmlElement(name = "MainFreight", required = true)
    protected String mainFreight;
    @XmlElement(name = "VasFreight", required = true)
    protected String vasFreight;
    @XmlElement(name = "CodFreight", required = true)
    protected String codFreight;
    @XmlElement(name = "CustomerCode", required = true)
    protected String customerCode;
    @XmlElement(name = "Weight", required = true)
    protected String weight;
    @XmlElement(name = "WeightConvert", required = true)
    protected String weightConvert;
    @XmlElement(name = "Width", required = true)
    protected String width;
    @XmlElement(name = "Length", required = true)
    protected String length;
    @XmlElement(name = "Height", required = true)
    protected String height;
    @XmlElement(name = "Opt", required = true)
    protected String opt;

    /**
     * Gets the value of the itemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * Sets the value of the itemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemCode(String value) {
        this.itemCode = value;
    }

    /**
     * Gets the value of the dataCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCode() {
        return dataCode;
    }

    /**
     * Sets the value of the dataCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCode(String value) {
        this.dataCode = value;
    }

    /**
     * Gets the value of the codAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodAmount() {
        return codAmount;
    }

    /**
     * Sets the value of the codAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodAmount(String value) {
        this.codAmount = value;
    }

    /**
     * Gets the value of the acceptancePoscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptancePoscode() {
        return acceptancePoscode;
    }

    /**
     * Sets the value of the acceptancePoscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptancePoscode(String value) {
        this.acceptancePoscode = value;
    }

    /**
     * Gets the value of the destinationPoscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationPoscode() {
        return destinationPoscode;
    }

    /**
     * Sets the value of the destinationPoscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationPoscode(String value) {
        this.destinationPoscode = value;
    }

    /**
     * Gets the value of the sendingTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendingTime() {
        return sendingTime;
    }

    /**
     * Sets the value of the sendingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendingTime(String value) {
        this.sendingTime = value;
    }

    /**
     * Gets the value of the senderFullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderFullname() {
        return senderFullname;
    }

    /**
     * Sets the value of the senderFullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderFullname(String value) {
        this.senderFullname = value;
    }

    /**
     * Gets the value of the senderAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderAddress() {
        return senderAddress;
    }

    /**
     * Sets the value of the senderAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderAddress(String value) {
        this.senderAddress = value;
    }

    /**
     * Gets the value of the senderTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderTel() {
        return senderTel;
    }

    /**
     * Sets the value of the senderTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderTel(String value) {
        this.senderTel = value;
    }

    /**
     * Gets the value of the receiverFullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverFullname() {
        return receiverFullname;
    }

    /**
     * Sets the value of the receiverFullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverFullname(String value) {
        this.receiverFullname = value;
    }

    /**
     * Gets the value of the receiverAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * Sets the value of the receiverAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverAddress(String value) {
        this.receiverAddress = value;
    }

    /**
     * Gets the value of the receiverTel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverTel() {
        return receiverTel;
    }

    /**
     * Sets the value of the receiverTel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverTel(String value) {
        this.receiverTel = value;
    }

    /**
     * Gets the value of the valueAddedServiceList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueAddedServiceList() {
        return valueAddedServiceList;
    }

    /**
     * Sets the value of the valueAddedServiceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueAddedServiceList(String value) {
        this.valueAddedServiceList = value;
    }

    /**
     * Gets the value of the mainFreight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainFreight() {
        return mainFreight;
    }

    /**
     * Sets the value of the mainFreight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainFreight(String value) {
        this.mainFreight = value;
    }

    /**
     * Gets the value of the vasFreight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVasFreight() {
        return vasFreight;
    }

    /**
     * Sets the value of the vasFreight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVasFreight(String value) {
        this.vasFreight = value;
    }

    /**
     * Gets the value of the codFreight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodFreight() {
        return codFreight;
    }

    /**
     * Sets the value of the codFreight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodFreight(String value) {
        this.codFreight = value;
    }

    /**
     * Gets the value of the customerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * Sets the value of the customerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCode(String value) {
        this.customerCode = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeight(String value) {
        this.weight = value;
    }

    /**
     * Gets the value of the weightConvert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightConvert() {
        return weightConvert;
    }

    /**
     * Sets the value of the weightConvert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightConvert(String value) {
        this.weightConvert = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLength(String value) {
        this.length = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the opt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpt() {
        return opt;
    }

    /**
     * Sets the value of the opt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpt(String value) {
        this.opt = value;
    }

}
