/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.postal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.opencps.postal.model.VnPostal;
import org.opencps.postal.model.VnPostalModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VnPostal service. Represents a row in the &quot;VnPostal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.opencps.postal.model.VnPostalModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VnPostalImpl}.
 * </p>
 *
 * @author nhanhlt
 * @see VnPostalImpl
 * @see org.opencps.postal.model.VnPostal
 * @see org.opencps.postal.model.VnPostalModel
 * @generated
 */
@JSON(strict = true)
public class VnPostalModelImpl extends BaseModelImpl<VnPostal>
	implements VnPostalModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vn postal model instance should use the {@link org.opencps.postal.model.VnPostal} interface instead.
	 */
	public static final String TABLE_NAME = "VnPostal";
	public static final Object[][] TABLE_COLUMNS = {
			{ "vnPostalId", Types.BIGINT },
			{ "posIdThuGom", Types.INTEGER },
			{ "soDonHang", Types.VARCHAR },
			{ "maKhachHang", Types.VARCHAR },
			{ "diaChiNguoiGui", Types.VARCHAR },
			{ "tenNguoiGui", Types.VARCHAR },
			{ "emailNguoiGui", Types.VARCHAR },
			{ "dienThoaiNguoiGui", Types.VARCHAR },
			{ "noiDungHang", Types.VARCHAR },
			{ "soTienCOD", Types.DOUBLE },
			{ "ghiChu", Types.VARCHAR },
			{ "ngayNhap", Types.VARCHAR },
			{ "posIdNhanTin", Types.INTEGER },
			{ "tenNguoiNhan", Types.VARCHAR },
			{ "diaChiNguoiNhan", Types.VARCHAR },
			{ "dienThoaiNguoiNhan", Types.VARCHAR },
			{ "maBuuGui", Types.VARCHAR },
			{ "donHangNoiHuyen", Types.BOOLEAN },
			{ "maTinhNhan", Types.INTEGER },
			{ "emailNguoiNhan", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table VnPostal (vnPostalId LONG not null primary key,posIdThuGom INTEGER,soDonHang VARCHAR(75) null,maKhachHang VARCHAR(75) null,diaChiNguoiGui VARCHAR(75) null,tenNguoiGui VARCHAR(75) null,emailNguoiGui VARCHAR(75) null,dienThoaiNguoiGui VARCHAR(75) null,noiDungHang VARCHAR(75) null,soTienCOD DOUBLE,ghiChu VARCHAR(75) null,ngayNhap VARCHAR(75) null,posIdNhanTin INTEGER,tenNguoiNhan VARCHAR(75) null,diaChiNguoiNhan VARCHAR(75) null,dienThoaiNguoiNhan VARCHAR(75) null,maBuuGui VARCHAR(75) null,donHangNoiHuyen BOOLEAN,maTinhNhan INTEGER,emailNguoiNhan VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table VnPostal";
	public static final String ORDER_BY_JPQL = " ORDER BY vnPostal.vnPostalId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VnPostal.vnPostalId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.opencps.postal.model.VnPostal"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.opencps.postal.model.VnPostal"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.opencps.postal.model.VnPostal"));

	public VnPostalModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _vnPostalId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVnPostalId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _vnPostalId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VnPostal.class;
	}

	@Override
	public String getModelClassName() {
		return VnPostal.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("vnPostalId", getVnPostalId());
		attributes.put("posIdThuGom", getPosIdThuGom());
		attributes.put("soDonHang", getSoDonHang());
		attributes.put("maKhachHang", getMaKhachHang());
		attributes.put("diaChiNguoiGui", getDiaChiNguoiGui());
		attributes.put("tenNguoiGui", getTenNguoiGui());
		attributes.put("emailNguoiGui", getEmailNguoiGui());
		attributes.put("dienThoaiNguoiGui", getDienThoaiNguoiGui());
		attributes.put("noiDungHang", getNoiDungHang());
		attributes.put("soTienCOD", getSoTienCOD());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("ngayNhap", getNgayNhap());
		attributes.put("posIdNhanTin", getPosIdNhanTin());
		attributes.put("tenNguoiNhan", getTenNguoiNhan());
		attributes.put("diaChiNguoiNhan", getDiaChiNguoiNhan());
		attributes.put("dienThoaiNguoiNhan", getDienThoaiNguoiNhan());
		attributes.put("maBuuGui", getMaBuuGui());
		attributes.put("donHangNoiHuyen", getDonHangNoiHuyen());
		attributes.put("maTinhNhan", getMaTinhNhan());
		attributes.put("emailNguoiNhan", getEmailNguoiNhan());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long vnPostalId = (Long)attributes.get("vnPostalId");

		if (vnPostalId != null) {
			setVnPostalId(vnPostalId);
		}

		Integer posIdThuGom = (Integer)attributes.get("posIdThuGom");

		if (posIdThuGom != null) {
			setPosIdThuGom(posIdThuGom);
		}

		String soDonHang = (String)attributes.get("soDonHang");

		if (soDonHang != null) {
			setSoDonHang(soDonHang);
		}

		String maKhachHang = (String)attributes.get("maKhachHang");

		if (maKhachHang != null) {
			setMaKhachHang(maKhachHang);
		}

		String diaChiNguoiGui = (String)attributes.get("diaChiNguoiGui");

		if (diaChiNguoiGui != null) {
			setDiaChiNguoiGui(diaChiNguoiGui);
		}

		String tenNguoiGui = (String)attributes.get("tenNguoiGui");

		if (tenNguoiGui != null) {
			setTenNguoiGui(tenNguoiGui);
		}

		String emailNguoiGui = (String)attributes.get("emailNguoiGui");

		if (emailNguoiGui != null) {
			setEmailNguoiGui(emailNguoiGui);
		}

		String dienThoaiNguoiGui = (String)attributes.get("dienThoaiNguoiGui");

		if (dienThoaiNguoiGui != null) {
			setDienThoaiNguoiGui(dienThoaiNguoiGui);
		}

		String noiDungHang = (String)attributes.get("noiDungHang");

		if (noiDungHang != null) {
			setNoiDungHang(noiDungHang);
		}

		Double soTienCOD = (Double)attributes.get("soTienCOD");

		if (soTienCOD != null) {
			setSoTienCOD(soTienCOD);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		String ngayNhap = (String)attributes.get("ngayNhap");

		if (ngayNhap != null) {
			setNgayNhap(ngayNhap);
		}

		Integer posIdNhanTin = (Integer)attributes.get("posIdNhanTin");

		if (posIdNhanTin != null) {
			setPosIdNhanTin(posIdNhanTin);
		}

		String tenNguoiNhan = (String)attributes.get("tenNguoiNhan");

		if (tenNguoiNhan != null) {
			setTenNguoiNhan(tenNguoiNhan);
		}

		String diaChiNguoiNhan = (String)attributes.get("diaChiNguoiNhan");

		if (diaChiNguoiNhan != null) {
			setDiaChiNguoiNhan(diaChiNguoiNhan);
		}

		String dienThoaiNguoiNhan = (String)attributes.get("dienThoaiNguoiNhan");

		if (dienThoaiNguoiNhan != null) {
			setDienThoaiNguoiNhan(dienThoaiNguoiNhan);
		}

		String maBuuGui = (String)attributes.get("maBuuGui");

		if (maBuuGui != null) {
			setMaBuuGui(maBuuGui);
		}

		Boolean donHangNoiHuyen = (Boolean)attributes.get("donHangNoiHuyen");

		if (donHangNoiHuyen != null) {
			setDonHangNoiHuyen(donHangNoiHuyen);
		}

		Integer maTinhNhan = (Integer)attributes.get("maTinhNhan");

		if (maTinhNhan != null) {
			setMaTinhNhan(maTinhNhan);
		}

		String emailNguoiNhan = (String)attributes.get("emailNguoiNhan");

		if (emailNguoiNhan != null) {
			setEmailNguoiNhan(emailNguoiNhan);
		}
	}

	@JSON(include = false)
	@Override
	public long getVnPostalId() {
		return _vnPostalId;
	}

	@Override
	public void setVnPostalId(long vnPostalId) {
		_vnPostalId = vnPostalId;
	}

	@JSON
	@Override
	public int getPosIdThuGom() {
		return _posIdThuGom;
	}

	@Override
	public void setPosIdThuGom(int posIdThuGom) {
		_posIdThuGom = posIdThuGom;
	}

	@JSON
	@Override
	public String getSoDonHang() {
		if (_soDonHang == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDonHang;
		}
	}

	@Override
	public void setSoDonHang(String soDonHang) {
		_soDonHang = soDonHang;
	}

	@JSON
	@Override
	public String getMaKhachHang() {
		if (_maKhachHang == null) {
			return StringPool.BLANK;
		}
		else {
			return _maKhachHang;
		}
	}

	@Override
	public void setMaKhachHang(String maKhachHang) {
		_maKhachHang = maKhachHang;
	}

	@JSON
	@Override
	public String getDiaChiNguoiGui() {
		if (_diaChiNguoiGui == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiNguoiGui;
		}
	}

	@Override
	public void setDiaChiNguoiGui(String diaChiNguoiGui) {
		_diaChiNguoiGui = diaChiNguoiGui;
	}

	@JSON
	@Override
	public String getTenNguoiGui() {
		if (_tenNguoiGui == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenNguoiGui;
		}
	}

	@Override
	public void setTenNguoiGui(String tenNguoiGui) {
		_tenNguoiGui = tenNguoiGui;
	}

	@JSON
	@Override
	public String getEmailNguoiGui() {
		if (_emailNguoiGui == null) {
			return StringPool.BLANK;
		}
		else {
			return _emailNguoiGui;
		}
	}

	@Override
	public void setEmailNguoiGui(String emailNguoiGui) {
		_emailNguoiGui = emailNguoiGui;
	}

	@JSON
	@Override
	public String getDienThoaiNguoiGui() {
		if (_dienThoaiNguoiGui == null) {
			return StringPool.BLANK;
		}
		else {
			return _dienThoaiNguoiGui;
		}
	}

	@Override
	public void setDienThoaiNguoiGui(String dienThoaiNguoiGui) {
		_dienThoaiNguoiGui = dienThoaiNguoiGui;
	}

	@JSON
	@Override
	public String getNoiDungHang() {
		if (_noiDungHang == null) {
			return StringPool.BLANK;
		}
		else {
			return _noiDungHang;
		}
	}

	@Override
	public void setNoiDungHang(String noiDungHang) {
		_noiDungHang = noiDungHang;
	}

	@JSON
	@Override
	public double getSoTienCOD() {
		return _soTienCOD;
	}

	@Override
	public void setSoTienCOD(double soTienCOD) {
		_soTienCOD = soTienCOD;
	}

	@JSON
	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@JSON
	@Override
	public String getNgayNhap() {
		if (_ngayNhap == null) {
			return StringPool.BLANK;
		}
		else {
			return _ngayNhap;
		}
	}

	@Override
	public void setNgayNhap(String ngayNhap) {
		_ngayNhap = ngayNhap;
	}

	@JSON
	@Override
	public int getPosIdNhanTin() {
		return _posIdNhanTin;
	}

	@Override
	public void setPosIdNhanTin(int posIdNhanTin) {
		_posIdNhanTin = posIdNhanTin;
	}

	@JSON
	@Override
	public String getTenNguoiNhan() {
		if (_tenNguoiNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenNguoiNhan;
		}
	}

	@Override
	public void setTenNguoiNhan(String tenNguoiNhan) {
		_tenNguoiNhan = tenNguoiNhan;
	}

	@JSON
	@Override
	public String getDiaChiNguoiNhan() {
		if (_diaChiNguoiNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiNguoiNhan;
		}
	}

	@Override
	public void setDiaChiNguoiNhan(String diaChiNguoiNhan) {
		_diaChiNguoiNhan = diaChiNguoiNhan;
	}

	@JSON
	@Override
	public String getDienThoaiNguoiNhan() {
		if (_dienThoaiNguoiNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _dienThoaiNguoiNhan;
		}
	}

	@Override
	public void setDienThoaiNguoiNhan(String dienThoaiNguoiNhan) {
		_dienThoaiNguoiNhan = dienThoaiNguoiNhan;
	}

	@JSON
	@Override
	public String getMaBuuGui() {
		if (_maBuuGui == null) {
			return StringPool.BLANK;
		}
		else {
			return _maBuuGui;
		}
	}

	@Override
	public void setMaBuuGui(String maBuuGui) {
		_maBuuGui = maBuuGui;
	}

	@JSON
	@Override
	public boolean getDonHangNoiHuyen() {
		return _donHangNoiHuyen;
	}

	@Override
	public boolean isDonHangNoiHuyen() {
		return _donHangNoiHuyen;
	}

	@Override
	public void setDonHangNoiHuyen(boolean donHangNoiHuyen) {
		_donHangNoiHuyen = donHangNoiHuyen;
	}

	@JSON
	@Override
	public int getMaTinhNhan() {
		return _maTinhNhan;
	}

	@Override
	public void setMaTinhNhan(int maTinhNhan) {
		_maTinhNhan = maTinhNhan;
	}

	@JSON
	@Override
	public String getEmailNguoiNhan() {
		if (_emailNguoiNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _emailNguoiNhan;
		}
	}

	@Override
	public void setEmailNguoiNhan(String emailNguoiNhan) {
		_emailNguoiNhan = emailNguoiNhan;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VnPostal.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VnPostal toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VnPostal)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VnPostalImpl vnPostalImpl = new VnPostalImpl();

		vnPostalImpl.setVnPostalId(getVnPostalId());
		vnPostalImpl.setPosIdThuGom(getPosIdThuGom());
		vnPostalImpl.setSoDonHang(getSoDonHang());
		vnPostalImpl.setMaKhachHang(getMaKhachHang());
		vnPostalImpl.setDiaChiNguoiGui(getDiaChiNguoiGui());
		vnPostalImpl.setTenNguoiGui(getTenNguoiGui());
		vnPostalImpl.setEmailNguoiGui(getEmailNguoiGui());
		vnPostalImpl.setDienThoaiNguoiGui(getDienThoaiNguoiGui());
		vnPostalImpl.setNoiDungHang(getNoiDungHang());
		vnPostalImpl.setSoTienCOD(getSoTienCOD());
		vnPostalImpl.setGhiChu(getGhiChu());
		vnPostalImpl.setNgayNhap(getNgayNhap());
		vnPostalImpl.setPosIdNhanTin(getPosIdNhanTin());
		vnPostalImpl.setTenNguoiNhan(getTenNguoiNhan());
		vnPostalImpl.setDiaChiNguoiNhan(getDiaChiNguoiNhan());
		vnPostalImpl.setDienThoaiNguoiNhan(getDienThoaiNguoiNhan());
		vnPostalImpl.setMaBuuGui(getMaBuuGui());
		vnPostalImpl.setDonHangNoiHuyen(getDonHangNoiHuyen());
		vnPostalImpl.setMaTinhNhan(getMaTinhNhan());
		vnPostalImpl.setEmailNguoiNhan(getEmailNguoiNhan());

		vnPostalImpl.resetOriginalValues();

		return vnPostalImpl;
	}

	@Override
	public int compareTo(VnPostal vnPostal) {
		long primaryKey = vnPostal.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VnPostal)) {
			return false;
		}

		VnPostal vnPostal = (VnPostal)obj;

		long primaryKey = vnPostal.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<VnPostal> toCacheModel() {
		VnPostalCacheModel vnPostalCacheModel = new VnPostalCacheModel();

		vnPostalCacheModel.vnPostalId = getVnPostalId();

		vnPostalCacheModel.posIdThuGom = getPosIdThuGom();

		vnPostalCacheModel.soDonHang = getSoDonHang();

		String soDonHang = vnPostalCacheModel.soDonHang;

		if ((soDonHang != null) && (soDonHang.length() == 0)) {
			vnPostalCacheModel.soDonHang = null;
		}

		vnPostalCacheModel.maKhachHang = getMaKhachHang();

		String maKhachHang = vnPostalCacheModel.maKhachHang;

		if ((maKhachHang != null) && (maKhachHang.length() == 0)) {
			vnPostalCacheModel.maKhachHang = null;
		}

		vnPostalCacheModel.diaChiNguoiGui = getDiaChiNguoiGui();

		String diaChiNguoiGui = vnPostalCacheModel.diaChiNguoiGui;

		if ((diaChiNguoiGui != null) && (diaChiNguoiGui.length() == 0)) {
			vnPostalCacheModel.diaChiNguoiGui = null;
		}

		vnPostalCacheModel.tenNguoiGui = getTenNguoiGui();

		String tenNguoiGui = vnPostalCacheModel.tenNguoiGui;

		if ((tenNguoiGui != null) && (tenNguoiGui.length() == 0)) {
			vnPostalCacheModel.tenNguoiGui = null;
		}

		vnPostalCacheModel.emailNguoiGui = getEmailNguoiGui();

		String emailNguoiGui = vnPostalCacheModel.emailNguoiGui;

		if ((emailNguoiGui != null) && (emailNguoiGui.length() == 0)) {
			vnPostalCacheModel.emailNguoiGui = null;
		}

		vnPostalCacheModel.dienThoaiNguoiGui = getDienThoaiNguoiGui();

		String dienThoaiNguoiGui = vnPostalCacheModel.dienThoaiNguoiGui;

		if ((dienThoaiNguoiGui != null) && (dienThoaiNguoiGui.length() == 0)) {
			vnPostalCacheModel.dienThoaiNguoiGui = null;
		}

		vnPostalCacheModel.noiDungHang = getNoiDungHang();

		String noiDungHang = vnPostalCacheModel.noiDungHang;

		if ((noiDungHang != null) && (noiDungHang.length() == 0)) {
			vnPostalCacheModel.noiDungHang = null;
		}

		vnPostalCacheModel.soTienCOD = getSoTienCOD();

		vnPostalCacheModel.ghiChu = getGhiChu();

		String ghiChu = vnPostalCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			vnPostalCacheModel.ghiChu = null;
		}

		vnPostalCacheModel.ngayNhap = getNgayNhap();

		String ngayNhap = vnPostalCacheModel.ngayNhap;

		if ((ngayNhap != null) && (ngayNhap.length() == 0)) {
			vnPostalCacheModel.ngayNhap = null;
		}

		vnPostalCacheModel.posIdNhanTin = getPosIdNhanTin();

		vnPostalCacheModel.tenNguoiNhan = getTenNguoiNhan();

		String tenNguoiNhan = vnPostalCacheModel.tenNguoiNhan;

		if ((tenNguoiNhan != null) && (tenNguoiNhan.length() == 0)) {
			vnPostalCacheModel.tenNguoiNhan = null;
		}

		vnPostalCacheModel.diaChiNguoiNhan = getDiaChiNguoiNhan();

		String diaChiNguoiNhan = vnPostalCacheModel.diaChiNguoiNhan;

		if ((diaChiNguoiNhan != null) && (diaChiNguoiNhan.length() == 0)) {
			vnPostalCacheModel.diaChiNguoiNhan = null;
		}

		vnPostalCacheModel.dienThoaiNguoiNhan = getDienThoaiNguoiNhan();

		String dienThoaiNguoiNhan = vnPostalCacheModel.dienThoaiNguoiNhan;

		if ((dienThoaiNguoiNhan != null) && (dienThoaiNguoiNhan.length() == 0)) {
			vnPostalCacheModel.dienThoaiNguoiNhan = null;
		}

		vnPostalCacheModel.maBuuGui = getMaBuuGui();

		String maBuuGui = vnPostalCacheModel.maBuuGui;

		if ((maBuuGui != null) && (maBuuGui.length() == 0)) {
			vnPostalCacheModel.maBuuGui = null;
		}

		vnPostalCacheModel.donHangNoiHuyen = getDonHangNoiHuyen();

		vnPostalCacheModel.maTinhNhan = getMaTinhNhan();

		vnPostalCacheModel.emailNguoiNhan = getEmailNguoiNhan();

		String emailNguoiNhan = vnPostalCacheModel.emailNguoiNhan;

		if ((emailNguoiNhan != null) && (emailNguoiNhan.length() == 0)) {
			vnPostalCacheModel.emailNguoiNhan = null;
		}

		return vnPostalCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(41);

		sb.append("{vnPostalId=");
		sb.append(getVnPostalId());
		sb.append(", posIdThuGom=");
		sb.append(getPosIdThuGom());
		sb.append(", soDonHang=");
		sb.append(getSoDonHang());
		sb.append(", maKhachHang=");
		sb.append(getMaKhachHang());
		sb.append(", diaChiNguoiGui=");
		sb.append(getDiaChiNguoiGui());
		sb.append(", tenNguoiGui=");
		sb.append(getTenNguoiGui());
		sb.append(", emailNguoiGui=");
		sb.append(getEmailNguoiGui());
		sb.append(", dienThoaiNguoiGui=");
		sb.append(getDienThoaiNguoiGui());
		sb.append(", noiDungHang=");
		sb.append(getNoiDungHang());
		sb.append(", soTienCOD=");
		sb.append(getSoTienCOD());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", ngayNhap=");
		sb.append(getNgayNhap());
		sb.append(", posIdNhanTin=");
		sb.append(getPosIdNhanTin());
		sb.append(", tenNguoiNhan=");
		sb.append(getTenNguoiNhan());
		sb.append(", diaChiNguoiNhan=");
		sb.append(getDiaChiNguoiNhan());
		sb.append(", dienThoaiNguoiNhan=");
		sb.append(getDienThoaiNguoiNhan());
		sb.append(", maBuuGui=");
		sb.append(getMaBuuGui());
		sb.append(", donHangNoiHuyen=");
		sb.append(getDonHangNoiHuyen());
		sb.append(", maTinhNhan=");
		sb.append(getMaTinhNhan());
		sb.append(", emailNguoiNhan=");
		sb.append(getEmailNguoiNhan());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(64);

		sb.append("<model><model-name>");
		sb.append("org.opencps.postal.model.VnPostal");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>vnPostalId</column-name><column-value><![CDATA[");
		sb.append(getVnPostalId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>posIdThuGom</column-name><column-value><![CDATA[");
		sb.append(getPosIdThuGom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDonHang</column-name><column-value><![CDATA[");
		sb.append(getSoDonHang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maKhachHang</column-name><column-value><![CDATA[");
		sb.append(getMaKhachHang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiNguoiGui</column-name><column-value><![CDATA[");
		sb.append(getDiaChiNguoiGui());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenNguoiGui</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiGui());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailNguoiGui</column-name><column-value><![CDATA[");
		sb.append(getEmailNguoiGui());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dienThoaiNguoiGui</column-name><column-value><![CDATA[");
		sb.append(getDienThoaiNguoiGui());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiDungHang</column-name><column-value><![CDATA[");
		sb.append(getNoiDungHang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soTienCOD</column-name><column-value><![CDATA[");
		sb.append(getSoTienCOD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayNhap</column-name><column-value><![CDATA[");
		sb.append(getNgayNhap());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>posIdNhanTin</column-name><column-value><![CDATA[");
		sb.append(getPosIdNhanTin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenNguoiNhan</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiNguoiNhan</column-name><column-value><![CDATA[");
		sb.append(getDiaChiNguoiNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dienThoaiNguoiNhan</column-name><column-value><![CDATA[");
		sb.append(getDienThoaiNguoiNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maBuuGui</column-name><column-value><![CDATA[");
		sb.append(getMaBuuGui());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>donHangNoiHuyen</column-name><column-value><![CDATA[");
		sb.append(getDonHangNoiHuyen());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maTinhNhan</column-name><column-value><![CDATA[");
		sb.append(getMaTinhNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailNguoiNhan</column-name><column-value><![CDATA[");
		sb.append(getEmailNguoiNhan());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VnPostal.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VnPostal.class
		};
	private long _vnPostalId;
	private int _posIdThuGom;
	private String _soDonHang;
	private String _maKhachHang;
	private String _diaChiNguoiGui;
	private String _tenNguoiGui;
	private String _emailNguoiGui;
	private String _dienThoaiNguoiGui;
	private String _noiDungHang;
	private double _soTienCOD;
	private String _ghiChu;
	private String _ngayNhap;
	private int _posIdNhanTin;
	private String _tenNguoiNhan;
	private String _diaChiNguoiNhan;
	private String _dienThoaiNguoiNhan;
	private String _maBuuGui;
	private boolean _donHangNoiHuyen;
	private int _maTinhNhan;
	private String _emailNguoiNhan;
	private VnPostal _escapedModel;
}